print("="*70)
print("Mesh vs Torus 拓扑对比（4×4 网格）")
print("="*70)

# 原始代码的连接（Torus 特性）
print("\n【原始代码（Torus 特性）】")
print("水平方向的'环绕'连接：")
print()
print("  Row 0:  0 - 1 - 2 - 3")
print("                      |  ← 错误的跨行连接")
print("  Row 1:  4 - 5 - 6 - 7")
print("                      |  ← 错误的跨行连接")
print("  Row 2:  8 - 9 -10 -11")
print("                      |  ← 错误的跨行连接")
print("  Row 3: 12 -13 -14 -15")
print()
print("错误连接: 3↔4, 7↔8, 11↔12")
print("这些连接让边界节点'环绕'到下一行，类似 Torus！")

# 修复后的连接（真正的 Mesh）
print("\n【修复后（真正的 Mesh）】")
print("没有跨行连接，边界是开放的：")
print()
print("  Row 0:  0 - 1 - 2 - 3")
print("          |   |   |   |")
print("  Row 1:  4 - 5 - 6 - 7")
print("          |   |   |   |")
print("  Row 2:  8 - 9 -10 -11")
print("          |   |   |   |")
print("  Row 3: 12 -13 -14 -15")
print()
print("边界节点各自独立，没有环绕")

# 完整的 Torus 拓扑（如果要实现的话）
print("\n【完整 Torus 拓扑（理论参考）】")
print("如果要实现真正的 Torus，还需要：")
print("  1. 水平环绕（行）：")
print("     - 3 ↔ 0 (Row 0 首尾相连)")
print("     - 7 ↔ 4 (Row 1 首尾相连)")
print("     - 11 ↔ 8 (Row 2 首尾相连)")
print("     - 15 ↔ 12 (Row 3 首尾相连)")
print()
print("  2. 垂直环绕（列）：")
print("     - 0 ↔ 12, 1 ↔ 13, 2 ↔ 14, 3 ↔ 15")
print("     (顶行和底行相连)")
print()
print("原始代码只实现了部分 Torus 特性（且是错误的）")

# 距离对比
print("\n【距离对比示例：Node 7 → Node 8】")
print(f"  位置: 7=(1,3), 8=(2,0)")
print(f"  Mesh 距离: |1-2| + |3-0| = 4 跳")
print(f"  原始代码（错误 Torus）: 1 跳（直接连接）")
print(f"  影响: 实际跳数 568 < 理论 640")
print()
print(f"  修复后（真正 Mesh）: 必须走 4 跳")
print(f"  例如: 7→6→5→4→8 或 7→11→10→9→8")

print("="*70)
